# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'zdravko'
primary_region = 'waw'

[build]
  builder = 'paketobuildpacks/builder:base'
  buildpacks = ['gcr.io/paketo-buildpacks/go']

[env]
  PORT = '8080'
  ROOT_URL = 'https://zdravko.mnts.dev'
  # Other are defined in secrets
  OAUTH2_ENDPOINT_TOKEN_URL = 'https://github.com/login/oauth/access_token'
  OAUTH2_ENDPOINT_AUTH_URL = 'https://github.com/login/oauth/authorize'
  OAUTH2_ENDPOINT_USER_INFO_URL = 'https://api.github.com/user'

  TEMPORAL_UI_HOST = 'temporal.process.zdravko.internal:8223'
  TEMPORAL_SERVER_HOST = 'temporal.process.zdravko.internal:7233'

[processes]
  server = "server"
  worker = "worker"
  temporal = "temporal"

[http_service]
  processes = ["server"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
