# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'zdravko'
primary_region = 'waw'

[build]
  builder = 'paketobuildpacks/builder:base'
  buildpacks = ['gcr.io/paketo-buildpacks/go']

[env]
  PORT = '8080'
  ROOT_URL = 'https://zdravko.fly.dev'
  SQLITE_DB_PATH = 'zdravko.db'
  # Other are defined in secrets
  OAUTH2_SCOPES = 'openid,profile,email'
  OAUTH2_ENDPOINT_TOKEN_URL = 'https://id.tjo.space/application/o/token/'
  OAUTH2_ENDPOINT_AUTH_URL = 'https://id.tjo.space/application/o/authorize/'
  OAUTH2_ENDPOINT_USER_INFO_URL = 'https://id.tjo.space/application/o/userinfo/'

[processes]
  server = "server"
  #worker = "worker"

[http_service]
  processes = ["server"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
