# fly.toml app configuration file generated for zdravko on 2024-02-17T21:20:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zdravko'
primary_region = 'waw'

[build]
  image = 'ghcr.io/mentos1386/zdravko:main'

[env]
  OAUTH2_ENDPOINT_AUTH_URL = 'https://github.com/login/oauth/authorize'
  OAUTH2_ENDPOINT_TOKEN_URL = 'https://github.com/login/oauth/access_token'
  OAUTH2_ENDPOINT_USER_INFO_URL = 'https://api.github.com/user'
  WORKER_API_URL = 'https://zdravko.mnts.dev'
  ROOT_URL = 'https://zdravko.mnts.dev'
  TEMPORAL_SERVER_HOST = 'server.process.zdravko.internal:7233'

  TEMPORAL_DATABASE_PATH = '/data/temporal-8.db'
  DATABASE_PATH = '/data/zdravko-8.db'

[processes]
  server = '--temporal --server'
  worker = '--worker'

[[mounts]]
  source = 'data'
  destination = '/data'
  processes = ['server']

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['server']

[[services]]
  protocol = 'tcp'
  internal_port = 7233
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['server']
  [[services.ports]]
      port = 7233
      handlers = ['tls']

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 512
  processes = ['server']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  processes = ['worker']
